services:
  ###############
  ## db server ##
  ###############
  db:
    #image: postgres:15-alpine
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: db-server
    # DB_USER, DB_PASSWORD come from ./.env (not git control)
    environment:
      #POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_DB: emsdb
      LANG: C.UTF-8
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      timeout: 2s
      retries: 10
      start_period: 5s
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    restart:
      on-failure
    tty: true
    stdin_open: true
    ports:
      - ${DB_DOCKER_PORTS}
    networks:
       ems_net:
         ipv4_address: ${DB_ADDRESS}
  #############
  ## develop ##
  #############
  #########################
  ## for backend(golang) ##
  #########################
  backend:
    #image: builder:latest
    container_name: backend
    build:
      context: ..
      dockerfile: ./trial-env/backend/Dockerfile
      #### USERNAME, USER_ID come from ./.env (not git control)
      args:
        - USERNAME=${USERNAME}
        - USER_ID=${USER_ID}
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      SS_PORT: ${SS_PORT}
      SS_PEM_FILE: ${SS_PEM_FILE}
      SS_KEY_FILE: ${SS_KEY_FILE}
      PERMIT_URLS: ${CS_URL}
    volumes:
      - ../ss:/home/${USER}/projects/ems/ss
      - ../scripts:/home/${USER}/projects/ems/scripts
      - ./go:/go
    working_dir: /home/${USER}/projects/ems/ss
    command: ../scripts/rungo ./cmd/manage/main.go
    healthcheck:
      test: "wget --no-check-certificate --spider ${SS_API_URL}/helth || exit 1"
      interval: 10s
      timeout: 8s
      retries: 5
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
    restart:
      on-failure
    tty: true
    stdin_open: true
    ports:
      - ${SS_DOCKER_PORTS}
    networks:
       ems_net:
         ipv4_address: ${SS_ADDRESS}
  #####################################
  ## for frontend (vite environment) ##
  #####################################
  frontend:
    #image: builder:latest
    container_name: frontend
    build:
      context: ..
      dockerfile: ./trial-env/frontend/Dockerfile
      #### USERNAME, USER_ID come from ./.env (not git control)
      args:
        - USERNAME=${USERNAME}
        - USER_ID=${USER_ID}
    environment:
      LANG: C.UTF-8
      TZ: Asia/Tokyo
      VITE_PORT: ${CS_PORT}
      VITE_API_URL: ${SS_API_URL}
    volumes:
      - ../cs:/home/${USER}/projects/ems/cs
    working_dir: /home/${USER}/projects/ems/cs
    command: npm run dev
    depends_on:
      backend:
        condition: service_healthy
    restart:
      on-failure
    tty: true
    stdin_open: true
    ports:
      - ${CS_DOCKER_PORT}
    networks:
       ems_net:
         ipv4_address: ${CS_ADDRESS}
#############################
## config internal network ##
#############################
networks:
  ems_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24
  #
  default:
    name: vlan_ems
    driver: bridge

